kind: pipeline
type: docker
name: default

steps:
- name: build_deploy
  privileged: true
  image: ianwalter/pnpm:v1.4.0
  volumes:
    - name: bonfire
      path: /bonfire:/bonfire
  commands:
  - pnpm install 
  - pnpm run build
  - ls .
  - ls /
  - ls /bonfire/
  - cat /bonfire/index.html
