kind: pipeline
type: docker 
name: deploy_dev
trigger:
  branch:
  - main

node:
  environment: ryali

volumes:
  - name: bonfire
    host:
      path: /bonfire

steps:
- name: build
  image: node:latest
  volumes:
    - name: bonfire
  commands:
    - npm install
    - npm run build
    - pwd
    - ls -la
    - ls -la ./build
    - ls -la /bonfire
    - rm -rf /bonfire/*
    - mv ./build/* /bonfire/
    - ls -la /bonfire
    
