kind: pipeline
type: docker 
name: deploy_dev
node:
  environment: ryali
trigger:
  branch:
  - main

steps:
- name: build
  image: node:latest
  commands:
    - npm install
    - npm run build
    - rm -rf /bonfire_dev/*
    - mv ./build/* /bonfire_dev/

---
kind: pipeline
type: docker 
name: deploy_prod
node:
  environment: ryali
trigger:
  event:
  - tag

steps:
- name: build
  image: node:latest
  commands:
    - npm install
    - npm run build
    - rm -rf /bonfire/*
    - mv ./build/* /bonfire/
