kind: pipeline
type: docker 
name: deploy_dev

trigger:
  branch:
  - main

steps:
- name: build
  image: node:latest
  commands:
    - npm install
    - npm run build

- name: deploy
  image: byteflair/scp
  commands:
    - mv ./build ./bonfire_dev_staging

    # Stage
    - ssh -tt 'light@5.75.206.84' 'sudo rm -rf /home/light/bonfire_dev_staging'
    - scp -r './bonfire_dev_staging' 'light@5.75.206.84:/home/light/'

    # Move to endpoint
    - ssh -tt 'light@5.75.206.84' 'sudo rm -rf /home/light/bonfire_dev/*'
    - ssh -tt 'light@5.75.206.84' 'sudo mv /home/light/bonfire_dev_staging/* /home/light/bonfire_dev/'

    # Remove staging
    - ssh -tt 'light@5.75.206.84' 'sudo rm -rf /home/light/bonfire_dev_staging'

---
kind: pipeline
type: docker 
name: deploy_prod

trigger:
  event:
  - tag

steps:
- name: build
  image: node:latest
  commands:
    - npm install
    - npm run build

- name: deploy
  image: byteflair/scp
  commands: 
    - mv ./build ./bonfire_staging

    # Stage
    - ssh -tt 'light@5.75.206.84' 'sudo rm -rf /home/light/bonfire_staging'
    - scp -r './bonfire_staging' 'light@5.75.206.84:/home/light/'

    # Move to endpoint
    - ssh -tt 'light@5.75.206.84' 'sudo rm -rf /home/light/bonfire/*'
    - ssh -tt 'light@5.75.206.84' 'sudo mv /home/light/bonfire_staging/* /home/light/bonfire/'

    # Remove staging
    - ssh -tt 'light@5.75.206.84' 'sudo rm -rf /home/light/bonfire_staging'
