kind: pipeline
type: docker 
name: deploy_dev

trigger:
  branch:
  - main

steps:
  - name: build
    image: node:latest
    commands:
      - npm install
      - npm run build

  - name: deploy
    image: byteflair/scp
    commands: 
      - scp -r ./build light@5.75.206.84:/home/light/bonfire_dev

---
kind: pipeline
type: docker 
name: deploy_prod

trigger:
  event:
  - tag

steps:
  - name: build
    image: node:latest
    commands:
      - npm install
      - npm run build

  - name: deploy
    image: byteflair/scp
    commands: 
      - scp -r ./build light@5.75.206.84:/home/light/bonfire
