kind: pipeline
type: docker
name: default

steps:
- name: build_deploy
  image: ianwalter/pnpm:v1.4.0
  commands:
  - pnpm install 
  - pnpm run build
  - rm -rv /data/bonfire
  - cp -rv ./build /data/bonfire/
