kind: pipeline
type: docker
name: default

steps:
- name: build_deploy
  privileged: true
  image: ianwalter/pnpm:v1.4.0
  volumes:
    - name: bonfire
      path: /home/light/bonfire:/bonfire/
  commands:
  - pnpm install 
  - pnpm run build
  - ls .
  - ls /
  - ls /home/
  - ls /home/light/
  - ls /data/
  - rm -rv /data/bonfire
  - cp -rv ./build /data/bonfire/
