kind: pipeline
type: docker 
name: deploy_dev

trigger:
  branch:
  - main

steps:
- name: build
  image: node:latest
  commands:
    - npm install
    - npm run build

- name: deploy
  image: byteflair/scp
  commands:
    - ssh 'light@5.75.206.84' 'rm -rf /home/light/bonfire_dev/*'
    - mv ./build ./bonfire_dev
    - scp -r './bonfire_dev/' 'light@5.75.206.84:/home/light/'

---
kind: pipeline
type: docker 
name: deploy_prod

trigger:
  event:
  - tag

steps:
- name: build
  image: node:latest
  commands:
    - npm install
    - npm run build

- name: deploy
  image: byteflair/scp
  commands: 
    - ssh 'light@5.75.206.84' 'rm -rf /home/light/bonfire/*'
    - mv ./build ./bonfire
    - scp -r './bonfire/' 'light@5.75.206.84:/home/light/'
