kind: pipeline
type: docker
name: default

steps:
- name: build_deploy
  image: ianwalter/pnpm:v1.4.0
  volumes:
    - name: bonfire
      path: /data/bonfire/:/data/bonfire
  commands:
  - pnpm install 
  - pnpm run build
  - ls .
  - ls /
  - ls /data/
  - rm -rv /data/bonfire
  - cp -rv ./build /data/bonfire/
