kind: pipeline
type: docker 
name: deploy
trigger:
  branch:
  - main

steps:
  - name: build
    image: node:latest
    commands:
      - npm install
      - npm run build

  - name: deploy


    commands: 
      - scp -r ./build light@5.75.206.84:/home/light/bonfire_dev
