kind: pipeline
type: docker
name: default


steps:
- name: build_deploy
  image: ianwalter/pnpm:v1.4.0
  privileged: true
  volumes:
    - /home/light/bonfire:/bonfire
  commands:
  - pnpm install 
  - pnpm run build
  - ls .
  - ls /
  - ls /home/
  - ls /home/light/
  - ls /data/
  - rm -rv /data/bonfire
  - cp -rv ./build /data/bonfire/
