name: Build and Deploy

on:
  push:
    tags:
      - '*'

jobs:
  build-and-deploy:
    runs-on: lina
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Deploy
        run: |
          mv ./build ./bonfire
          ssh rylai "rm -rf /home/light/nginx-reverse-proxy-manager/sites/bonfire/*"
          scp -r './bonfire/.' 'rylai:/home/light/nginx-reverse-proxy-manager/sites/bonfire/'
